# Generated by Django 2.1 on 2018-08-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
