# Generated by Django 2.1 on 2018-08-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Customers'),
        ),
    ]
